
# Writing with a Readable Style
 
While *structure* has to do with the reader’s ability to understand the document as a
whole, including paragraphs, *style* has to do with readability at the sentence and word
level.

## The Importance of a Readable Style

No matter how technical your document, your audience won’t understand the content unless your sentences are easy to understand and your words are chosen precisely. Your style is a blend of these elements:

- the way in which you construct each sentence
- the length of your sentences
- the way in which you connect sentences
- the words and phrases you choose
- the tone you convey

Inefficient style makes readers work harder than they should. Style can be inefficient for many reasons but especially when it does the following:

- makes the writing impossible to interpret
- takes too long to make the point
- reads like a story from primary school
- sounds stuffy and impersonal

Regardless of the cause, inefficient style results in writing that is less informative and less persuasive than it should be. Also, inefficient style can be unethical when it confuses or misleads the audience, whether intentionally or unintentionally. Therefore, take the time to write with a readable style, using the strategies described in the following sections: writing clearly, writing concisely, writing fluently, and writing personably.

## Writing Clearly

Clear writing enables people to read each sentence only once to fully grasp its meaning. Strategies for writing clearly include avoiding ambiguous pronoun references, avoiding ambiguous modifiers, using active voice whenever possible, using passive voice selectively, avoiding nominalizations, unstacking nouns, and avoiding unnecessary jargon. Avoiding Ambiguous Pronoun References

Pronouns (he, she, it, their, and so on) must clearly refer to the nouns they replace; otherwise, the sentence will be ambiguous and readers will puzzle over your intended meaning. For example, consider the following sentence, in which the reader is unable to discern whether Jack or his assistant is competitive:

> Jack resents his assistant because he is competitive.

Depending on whether the referent for “he” is Jack or his assistant, the sentence can be clarified:

> Because his assistant is competitive, Jack resents him.

or

> Because Jack is competitive, he resents his assistant.


### Avoiding Ambiguous Modifiers

A *modifier* is a word (usually an adjective or adverb) or a group of words (usually a phrase or clause) that provides information about other words or groups of words. If a modifier is too far from the words it modifies, the message can be ambiguous. For instance, in the following sentence, the reader cannot discern whether “only” modifies “press” or “emergency”:

> Only press the red button in an emergency.

If, however, the writer repositions the modifier, the sentence becomes clear:

> Press only the red button in an emergency.

or

> Press the red button in an emergency only.



### Using Active Voice Whenever Possible

In general, readers understand the meaning more quickly and clearly when the writer uses active voice (“I did it”) rather than the passive voice (“It was done by me”). In active voice sentences, a clear agent performs a clear action on a recipient, as in the
following example:

> Felix lost your report.

Passive voice, by contrast, reverses this pattern, placing the recipient of the action (i.e., report, in the previous example) in the subject slot, as in the following sentence:

> Your report was lost by Felix.

Note that passive voice adds a form of the verb “be” (“was”) next to the actual verb.

Some writers mistakenly rely on passive voice because they think it sounds more objective and important. But passive voice makes sentences wordier and harder to understand.

In addition, passive voice sometimes obscures the subject of the sentence, as in the following example:

> Your report was lost.

Passive voice is unethical if it obscures the person or other agent who performed the action when the person or agent responsible should be identified. In the above example, “Your report was lost” leaves out the responsible party. (Who lost the report?) For these reasons, favor the active voice in most writing situations.


### Using Passive Voice Selectively

There are times when the passive voice is appropriate: for instance, when the subject is not known or when the object is more important than the subject. For example, if a group of scientists performed an experiment and wanted to explain the results, they might write the following:

> The data were analyzed, and the findings were discussed.

Even here, active voice (“We analyzed the data...”) would be preferable. But if it is clear who analyzed the data or truly not important who did the work, passive voice might be acceptable.

Passive voice can also ease the blow a direct sentence might deliver:
> You have not paid your bill.

To be indirect and less offensive, the writer may choose passive voice instead:

> Your bill has not been paid.

Consider this technique when you want to avoid a blunt or hostile tone. But in general, to convey clear, readable technical information, use active voice.



### Avoiding Nominalizations

A nominalization is a noun that would be easier to understand as a verb. Verbs are generally easier to read because they signal action that can be visualized. You can usually spot a nominalization in two ways. First, look for words with -tion endings. Second, look for sentences in which the “[noun] of [noun]” formula appears. Following is an example of each type of nominalization:

> My recommendation is for a larger budget.

> The managing of this project is up to me.

To fix the -tion problem, strike the ending to find the root verb (“recommend”) and rewrite the sentence in a more direct form. To fix the “[noun] of [noun]” problem, identify the root verb form (“manage”) and create a more accessible sentence. Following are improved versions of the above sentences:

> recommend a larger budget.

> manage this project.


### Unstack Modifying Nouns

Too many nouns in a row can create confusion for readers. One noun can modify another (as in “software development”). But when two or more nouns modify a noun, the string of words becomes “stacked”—in other words, hard to read and ambiguous. For example:

> Be sure to leave enough time for today’s training session participant evaluation.

In the previous sentence, the reader is left unsure whether evaluation is of the session or of the participants. With no articles, prepositions, or verbs to unstack the nouns, readers cannot sort out the relationships among the nouns. To fix the problem, separate the stacked nouns by changing some nouns into verb forms where appropriate, as in the following example:

> Be sure to leave enough time for participants to evaluate today’s training session.

or

> Be sure to leave enough time to evaluate the participants in today’s training session.




### Avoiding Unnecessary Jargon

Every profession has its own shorthand and accepted phrases and terms. Among specialists, these terms are an economical way to communicate. For example, “stat” (from the Latin statim, “immediately”) is medical jargon for “drop everything and deal with this emergency.” Jargon can be useful in communications among specialists. However, to avoid confusion, use jargon only when you know your audience will understand it and not simply to sound important or pretentious. Consider the following sentence:

> We will bilaterally optimize our efforts on this project.

Clearly, that writer meant to sound important, but to most readers, the sentence is simultaneously meaningless and pretentious.

Following is a clear and simple version:

> We will cooperate on this project.



## Writing Concisely

Concise writing provides readers with all of the information they need but without any needless filler. Strategies for writing concisely include avoiding wordiness and eliminating redundancy and repetition.

### Avoiding Wordiness

Wordiness is often unavoidable in a first draft, when a writer is simply trying to get thoughts down on the page. For your readers, however, wordiness is distracting and detracts from a writer’s credibility. When you edit your document, go through each sentence and work to eliminate excess words.

Wordiness has multiple causes: First, some writers habitually use needless phrases that can be reduced to one word:

> at a rapid rate = rapidly

> due to the fact that = because

> aware of the fact that = know

> in close proximity to = near

> the majority of = most

Second, many writers tend to start sentences with “there is,” “there are,” and “it is,” which can often be eliminated:

> There is a danger of explosion in Number 2 mineshaft. = Number 2 mineshaft is in danger of exploding.

> It is necessary to complete both sides of the form. = Please complete both sides of the form.

Third, writers often gravitate to weak verbs, such as all forms of the verb “to be” (“am,” “are,” “is,” etc.), “give,” “make,” “come,” and “take.” These verbs need to be combined with other words to express fuller meaning, but they can easily be replaced with stronger verbs that can stand on their own:

> has the ability to = can

> make an assumption = assume



> come to the conclusion that = conclude

> give a summary of = summarize

> take action = act

Fourth, writers often overuse prepositional phrases, which can easily be reduced to one or two words:

> with the exception of = except for

> in the near future = soon

> at the present time = now

> in the course of = during

> in the process of = during (or in)

Finally, many writers pad their writing by using clutter words (such as “very,” “quite,” “somewhat,” “really,” “actually”), needless qualifiers (“I think,” “in my opinion,” “it seems”), and unnecessary prefaces (“As far as lam concerned,” “the purpose of this is”) that add no meaning to a sentence. Of course, if you are expressing a tentative position on a complex issue, do use a qualifier (“I think,” “it seems”) as appropriate.


### Eliminating Redundancy and Repetition

A redundant expression says the same thing twice, in different words, whereas a repetition says the same thing twice or more in the same words. Following are examples of each, which can be fixed simply through cutting out the bracketed words.


## Writing Fluently

When you write fluently, you will hold your readers’ interest and attention by making clear connections between ideas and by reducing monotony. Strategies for writing fluently include combining related ideas, varying sentence construction and length, and using parallel structure.

### Combining Related Ideas

Readers who are forced to trudge through a series of short, choppy sentences will not only lose interest but will also fail to see how ideas are meant to be related or which ideas should receive emphasis. For example, the following string of five short sentences makes for dull reading. In addition, it forces readers to invent transitions between ideas and decide which points are most important:

> Running can be healthful. You need the right equipment. Well-fitting shoes are important. You take the chance of injuring your legs. Your knees are especially prone to injury.

In contrast, the following two-sentence revision reads more smoothly and places a stronger emphasis on the importance of having the right jogging shoes:

> Running can be healthful if you have the right equipment. Shoes that fit well are particularly important because they prevent injury to your legs, especially your knees.

### Varying Sentence Construction and Length

While you should combine short, choppy sentences into longer, more fluid versions, you don’t want to create a string of unvaried longer sentences. Readers will find these just as monotonous, and they will also have a hard time determining which points are meant to receive emphasis. For example, the following two longer sentences are unvaried and dull, and at the same time the reader is forced to decide which of the five points made is the most important: 

> Two drawbacks of diesel engines are that they are difficult to start in cold weather and cause sulfur dioxide pollution. In addition, they give off noise, emit an unpleasant odor, and cause vibrations.

In contrast, the following two-sentence revision reads less monotonously and incorporates one short sentence to place special emphasis on sulfur dioxide pollution:

> Diesel engines have a number of drawbacks, including cold weather starting difficulties, noisiness, odor, and vibrations. More seriously, they also cause sulfur dioxide pollution.


### Using Parallel Structure

Parallel structure is a fancy way of saying that similar items should be expressed in similar grammatical form. Without parallelism, readers will lose attention, being mentally forced to “fix” the grammatical fluency of your sentence. For example, the structure of the following sentence is not parallel:

> She likes many outdoor activities, including running, kayaking, and to design new hiking trails.

This sentence is essentially a list of items. The first two items, “running” and “kayaking,” are expressed as gerunds (verbs converted into nouns by using -ing endings). The third item, “to design,” is not a gerund but a verb followed by an object. To make this sentence parallel and increase its fluency you would revise as follows:

> She likes many outdoor activities, including running, kayaking, and designing new hiking trails.




## Writing Personably

When you write in a personable manner, you connect directly with your readers and avoid inadvertently offending them. Strategies for writing personably include adjusting your tone and avoiding sexist and biased language.

### Adjusting Your Tone

Your tone is your personal stamp—the personality that takes shape between the lines. The tone you create depends on 1) the distance you impose between yourself and the reader, and 2) the attitude you show toward the subject. To increase the likelihood of bringing readers over to your side, see the Strategies that follow.



### Strategies for Deciding about Tone {-

- **Determine if you want a formal, semiformal, or informal tone.** You may prefer a formal tone when writing to superiors, professionals, or academics (depending on what you think they expect), a semiformal tone for colleagues and subordinates (depending on how close you feel to your readers), or a slightly informal tone when you want your writing to be conversational.
- **Remain consistent.** Once you’ve determined the appropriate overall tone of the document, stay with it throughout.
- **Address readers directly.** Prefer the personal pronouns “you” and “your” to connect with readers.
- **Use “I” and “we” when appropriate.** Instead of disappearing behind your writing, use “I” and “we” to connect with your readers.
- **Prefer the active voice.** Show confidence and directness by using active rather than passive voice.
- **Emphasize the positive**. Avoid a negative tone when conveying unpleasant information.
- **Always avoid an overly informal tone.** Achieving a conversational tone does not mean relying on substandard usage (“He ain’t got none”), profanity (“This idea sucks”), and colloquialisms (“OK,” “a lot,” “snooze”). Pay special attention to tone when using email (see Chapter 18 for more on email tone and style).


### Avoiding Biased Language

Language that is offensive or makes unwarranted assumptions is inappropriate for workplace communication and may harm the reputation of a company or organization. For example, letters addressed to “Dear Sir” may leave an unfavorable impression of the company on all readers but especially on women. Unnecessary mention of gender, marital status, physical appearances, and ethnicity may also alienate readers.

### Strategies for Unbiased Usage {-}

- **Use neutral expressions.** Use “chair” or “chairperson” rather than “chairman” and “postal worker” rather than “postman.”
- **Don’t mention gender if it is not relevant.** Don’t use “the female police officer” unless you are talking about police officers in the context of gender.
- **Avoid sexist pronouns.** You can avoid using a sexist pronoun by revising the sentence (“A writer who revises will succeed” rather than “A writer will succeed if he revises”), by using a plural form (“Writers will succeed if they revise”), or by occasionally using paired pronouns (“A writer will succeed if he or she revises”).
- **Drop condescending diminutive endings.** Avoid words such as “poetess” and “majorette” and simply use “poet” and “major” instead.
- **Use “Ms.”** Unless you know that a person prefers a traditional title, avoid “Mrs.” and “Miss.” Males are not identified by marital status, nor should females have to be.
