--- 
title: "WRIT-221: Intermediate Tech Writing"
author: "River Kelly"
# date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---
```{r setup}

colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color, x)
  } else {
    sprintf("%s",x)
  }
}

```

# Course Overview {-}

Writing 221 provides a critical introduction to the genres, processes and ethics of writing in technical and professional settings. This includes strategies for negotiating rhetorical situations, responding effectively to others’ work, planning and conducting research as well as making basic decisions about style and document design. We will write individually as well as collaboratively in small groups—as technical writing is often done in teams rather than by individuals.

## Learning Outcomes {-}

1. Perform audience analysis (thereby increasing rhetorical awareness) to create documents that effectively communicate to a specific audience.
2. Create documents in a range of genres that effectively address a variety of professional rhetorical situations, including professional letters; memos; proposals; resumes; and web pages.
3. Use appropriate organizational strategies, both visual and written, in professional documents; design and create multi-modal technical documents using appropriate software
4. Work in teams to establish collaborative goals, solve problems, and develop end products.
5. Reflect on and explain particular design and communication decisions.
6. Edit documents for clarity, correctness and audience.


## Course Structure {-}

Below I explain course structure—i.e. the folders listed under **Content** and how to use them. If you have any questions, don’t hesitate to email me. If you are new to D2L, I recommend tutorials, which can be found at [http://www.montana.edu/ecat/](http://www.montana.edu/ecat/){target="_blank"}.

 

**FIRST, please read** the [Course Syllabus](assets/WRIT 221 Syllabus.pdf){target="_blank"} carefully so that you understand learning outcomes, grading policies and general course expectations. Required texts are listed there, too. 

**SECOND, take a peak at the** [The Weekly Assignments Calendar](https://ecat.montana.edu/content/enforced1/617795-WRIT_221_801802_202070_CL/Weekly%20Assignment%20Calendar.html?ou=617795){target="_blank"}, which is subject to change depending on class pacing but will give you a sense of workload and big-picture responsiblites. Please note that the term is divided as follows:

- `r colorize("**Weeks 1-5**", "orange")`:  You will discuss topics in Class Discussions #1-#2; then write documents individually and share them in small workshop groups called Writing Workshops.
- `r colorize("**Week 6**", "orange")`: Your Writing Workshop group will collaborate on Assignment #4  and submit it for completion credits and revision suggestions.
- `r colorize("**Week 7**", "orange")`: Individually, you will draft and submit Assignment #5, a resume and cover letter for a grade.
- `r colorize("**Weeks 8**", "orange")`: Midterm Refection, which requires reading and contribution to Class Discussion #3.
- `r colorize("**Weeks 9-12**", "orange")`: You will work in small groups on a month-long project, Assignment #6, which requires efficient and effective collaboration—all requirements of work-place writing.
- `r colorize("**Weeks 13-15**", "orange")`: individually, you will work on Assignment #7, your Final Portfolio.
  
  
**AT THE START OF EACH WEEK, please proceed through D2L in the following manner**:

1. Monday morning, click on the appropriate weekly module (with dates) and open **Instructor's Notes**, where I detail all reading and writing assignments for that week taken in a table. Below that I touch upon key points from that week’s reading. Conceptually, my **Instructor's Notes** take the place of an in-class lecture.
2. Complete the **reading assignments**, then review my notes about them.
3. Complete the **writing assignment(s)**. *Some weeks you will post these assignments to the Class Discussion Board; sometimes you will share with your Writing Workshop; other times you will submit to the Assignments folder for a grade. (See next section for an outline of this process.)*
4. Finally, follow the module link to the appropriate **Discussion Board**.


**DISCUSSION BOARDS**: Each week, once you have completed your readings, you will be asked to contribute to a Class Discussion or share writing in a Writing Workshop. Both are outlined below. 

- **Class Discussions #1-4**: These are whole-class (25 students) discussions that require 1-2 posts per person. Specific directions and due dates will be listed in the discussion thread and in my Weekly Announcement. `r colorize("Each discussion is worth up to 5 points", "green")`.
- **Writing Workshops #1-3**: You will work in groups of 5-6 students in the first half of the term sharing documents. In most instances, you will post your draft in your workshop by midnight Sunday and then respond to a peer draft by the following Wednesday at midnight. These discussion forums are meant to provide you with specific readers (i.e. your peers and me, your instructor) as well as the opportunity to receive and provide valuable feedback. I will provide substantial feedback on one document from each workshop group per week; these comments, even if not given on your work, are meant to help every student learn technical writing skills. `r colorize("Each workshop is worth up to 5 points", "green")`.
- **Non-Profit Project Discussion Board**: During weeks 9 –12, you will work in small groups creating a series of documents for a non-profit organization. Because you're using skills we've practiced all term and you have four weeks, this project is worth `r colorize("50 points", "green")`. 

 

**Technical Writing Assignments #1-7**: As assigned, I will post assignment sheets with detailed objectives and format requirements in the weekly modules. I will explain these in my Instructor's Notes at the start of the week when they are due and you will either be asked to share your work in a Writing Workshop or submit to me (for a grade) in Assignments.

- **Naming Documents**: Name your file "Last Name Assignment Name" before uploading it to any discussion board or Assignment folder; this helps readers and your instructor keep track of the author once it's downloaded. For instance, for Assignment #1 I would save my document as "Carnwath_Instructions" or "Carnwath_Assignment#1."
- **Teacher Drafts**: During weeks 6 and 7, you will turn in drafts for completion credits out of 10 and substantial instructor feedback. Week 6 is a group assignment (completed with members in your Writing Workshop) and week 7’s assignment will be done individually—both will be submitted via **Assignments**. My feedback will guide revisions (should you include these documents in the Final Portfolio) as well as continue to give you a sense of my expectations as an evaluator and technical writer.
- **Assignment Folder**: Assignments 4 - 7 will be submitted through the **Assignments** folder. This includes Teacher Drafts (10 points each); the Non-Profit Group Project (50 points); and your Final Portfolio (100 points). *(Assignments 1-3 will be shared with peers in Writing Workshops for feedback.)*

**Course Readings**: In addition to select readings from your two textbooks, I require additional readings throughout the term and will post these in the weekly modules as assigned.

**Video Notes**: As needed, I will post short (3-minute) videos to guide drafting and revision—as well as offer extra tips and reminders.

## Discussion Board Expectations & Rubric {-}

*(Adopted from the George Mason Writing Center)*

Treat your discussion board post as any other written paper or response for school. You will want to establish a process that works for you and use that process to produce engaging ideas that contribute to the online conversation you are having with your classmates and your professor. You shouldn’t just strive for completion, but also discussion and engagement.

 

### Before you begin: {-}

- Read your prompt or discussion question carefully—pay attention to word count, citation requirements, and specific guidelines such as due dates and response requirements. Are you just answering one question or do you have to answer a question and then respond to others?
- Set an agenda—making a schedule will help you stay on task and not get behind, especially with two-part due dates and follow up responses.
- Narrow down what exactly you should be accomplishing in your post (are you arguing for or against something, are you stating your opinion, are you summarizing a reading?).

### Drafting the post: {-}

- Before you begin take a few minutes to observe your peer’s posts. This will allow you to see what other people are saying and give you the opportunity to even quote some of your peers.
- Begin by drafting your post in MS Word or another application. This will give you the chance to explore your ideas without the fear of an accidental submission before you are finished.
- Use titles or headings to lead the reader through your post.
- Use a warm opening. Don’t be too abrupt or forward right off the bat. Allow your reader time to get “into” your post without feeling lost or overwhelmed.
- Avoid jokes. Because you are not in a face-to-face environment, it’s easier for someone to take something you say the wrong way.
- Consider your audience. Your post will be read by your professor and your peers, so be sure to maintain a professional tone.

### Responding to a post: {-}

- Address your classmates by their names when responding to their posts.
- Don’t dominate the conversation. Ask questions and point out specific details that you found interesting about the other posts.
- Keep in mind that your goal in responding is rooted in keeping the conversation going.
- Quote or restate a few ideas from the post you are responding to.
- Be respectful and non-confrontational.
- Be as specific as possible to encourage discussion.
